ground-plane:
    type: "infinite-plane"
    mu: 0.5
    restitution: 0.0
    #height: 0.5
    height: 0.0
    graphicsSize: [20,20] # how large the plane appears
    checkers: [40,40]     # how many checkers are on the plane

#myStairs
stairs-1:
    type: "stairs"
    steps: 10
    rise: 0.105 # unit: meters
    run: 0.285 
    width: 1.2
    mu: .7
    restitution: 0
    #position: [0.5, 0, -0.52]
    position: [0.30, 0, 0.0]
    orientation: [0, 0, 0]
    transparent: 0